name: HTTP Status Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check_http_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check URL Status
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" https://httpstat.us/200)
          echo "HTTP Status Code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Unexpected HTTP status code. Expected 200."
            exit 1
          fi
          echo "The website returned the expected 200 status code."



